Application:
    device_name             :   'MoPS'
    device_version          :   "v1.0"
    adc_channels            : {"3":"V",
                               "4":"V",
                               "5":"V",
                               "6":"V",
                               "7":"V",
                               "8":"V",
                               "9":"V",
                               "10":"V",
                               "11":"V",
                               "12":"V",
                               "13":"V",
                               "14":"V",
                               "15":"V",
                               "16":"T",
                               "17":"V",
                               "18":"V",
                               "19":"T",
                               "20":"V",
                               "21":"V",
                               "22":"T",
                               "23":"V",
                               "24":"T",
                               "25":"V",
                               "26":"V",
                               "27":"T",
                               "28":"V",
                               "29":"V",
                               "30":"V",
                               "31":"V",
                               "32":"V",
                               "33":"V",
                               "34":"V"} 
    icon_dir                :   "graphics_Utils/icons/icon_mops.png"
    nodeIds                 :   [1]
    index_items             :   {
                                "------" :  {"description_items" :"<html><b>-----</b></html>",
                                             "subindex_items"    :{     "-----":"<html><b>-----</b></html>"}} 
                               ,"0x1000" :  {"description_items" :"<html><b> Device type</b> [Default 191(hex)]</b></html>",
                                             "subindex_items"    :{     "0":"<html><b>-----</b></html>"}}      
                               ,"0x1001" :  {"description_items" :"<html><b> Error register</b> [Default 0]</b></html>",
                                             "subindex_items"    :{     "0":"<html><b>-----</b></html>"}}
                               ,"0x1005" :  {"description_items" :"<html><b> COB-ID SYNC</b> [Default 80(hex)]</b></html>",
                                             "subindex_items"    :  {   "0":"<html><b>-----</b></html>"}}
                               ,"0x1014" :  {"description_items" :"<html><b> COB-ID EMCY</b> [Default 80(hex)+NodeId]</b></html>",
                                             "subindex_items"    :  {   "0":"<html><b>-----</b></html>"}}
                                            
                               ,"0x1018" :  {"description_items" :"<html><b> Identity object needs</b></html>",
                                             "subindex_items"    :  {   "0":"<html><u>subindex 0:</u> Number of entries [Default 1]</html>",
                                                                        "1":"<html><u>subindex 1:</u> Vendor Id [Default 12345678(hex)+NodeId]</p></html>"}}                                          

                               ,"0x1200" :  {"description_items" :"<html><b>Server SDO parameter 0</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0:Number of entries [Default 2]</u></html>",
                                                                        "1":"<html><u>subindex 1:COB-ID client to server [Default 600 (hex) + NodeId]</u></html>",
                                                                        "2": "<html><u>subindex 2:COB-ID server to client [Default 580 (hex) + NodeId]</u></html>"}}
                               ,"0x1800" :  {"description_items" :"<html><b>TPDO communication parameter 0 </b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0:</u> Number of entries [Default 6]</html>",
                                                                        "1":"<html><u>subindex 1:</u> COB-ID [Default 180 (hex) + NodeId]</html>",
                                                                        "2":"<html><u>subindex 2:</u>Transmission type[Default FE (hex)]</html>",
                                                                        "3":"<html><u>subindex 3:</u> Inhibit time [Default 0]</html>",
                                                                        "4":"<html><u>subindex 4:</u> Reserved[Unused]</html>",
                                                                        "5": "<html><u>subindex 5:</u> Event timer [Default 0]</html>",
                                                                        "6":"<html><u>subindex 6:</u> SYNC start value[Default 0]</html>"}}
                               ,"0x1801" : {"description_items" :"<html><b> TPDO communication parameter 1</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0:</u> Number of entries [Default 6]</html>",
                                                                        "1":"<html><u>subindex 1:</u> COB-ID [Default 280 (hex) + NodeId]</html>",
                                                                        "2":"<html><u>subindex 2:</u>Transmission type[Default FE (hex)]</html>",
                                                                        "3":"<html><u>subindex 3:</u> Inhibit time [Default 0]</html>",
                                                                        "4":"<html><u>subindex 4:</u> Reserved[Unused]</html>",
                                                                        "5":"<html><u>subindex 5:</u> Event timer [Default 0]</html>",
                                                                        "6":"<html><u>subindex 6:</u> SYNC start value[Default 0]</html>"}}
                               ,"0x1A00" : {"description_items" :"<html><b> TPDO mapping parameter 0</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0:</u> Number of entries [Default 1]</html>",
                                                                        "1":"<html><u>subindex 1:</u> PDO mapping entry [Default 21000020(hex)]</html>"}}                                        
                               ,"0x1A01" : {"description_items" :"<html><b> TPDO mapping parameter 1</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0:</u> Number of entries [Default 1]</html>",
                                                                        "1":"<html><u>subindex 1:</u> PDO mapping entry [Default 21010030(hex)]</html>"}}                                       
                               ,"0x2001" : {"description_items" :"<html><b> ADC trimming bits</b></html>",
                                            "subindex_items"    :  {"0":"<html><b>-----</b></html>"}}                                                                                               
                               ,"0x2100":  {"description_items" :"<html><b> Read monitoring values of all FEs</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u></u></html>"}}
                               ,"0x2310":  {"description_items" :"<html><b> Read other monitoring values</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0</u>:Number of entries [Default 3]</html>",
                                                                        "1":"<html><u>subindex 1</u>:VMODGND</html>",
                                                                        "2":"<html><u>subindex 1</u>:VCANSEN</html>",
                                                                        "3":"<html><u>subindex 2</u>:VGNDSEN</html>"}}
                               ,"0x2400":  {"description_items" :"<html><b>Internal ADC channels</b></html>",
                                            "subindex_items"    :  {    "0":"<html><u>subindex 0</u>:Number of entries [Default 40]</html>",
                                                                        "1":"<html><u>subindex 1</u>:ADCCh3</html>",
                                                                        "2":"<html><u>subindex 2</u>:ADCCh4</html>",
                                                                        "3":"<html><u>subindex 3</u>:ADCCh5</html>",
                                                                        "4":"<html><u>subindex 4</u>:ADCCh6</html>",
                                                                        "5":"<html><u>subindex 5</u>:ADCCh7</html>",
                                                                        "6":"<html><u>subindex 6</u>:ADCCh8</html>",
                                                                        "7":"<html><u>subindex 7</u>:ADCCh9</html>",
                                                                        "8":"<html><u>subindex 8</u>:ADCCh10</html>",
                                                                        "9":"<html><u>subindex 9</u>:ADCCh11</html>",
                                                                        "A":"<html><u>subindex A</u>:ADCCh12</html>",
                                                                        "B":"<html><u>subindex B</u>:ADCCh13</html>",
                                                                        "C":"<html><u>subindex C</u>:ADCCh14</html>",
                                                                        "D":"<html><u>subindex D</u>:ADCCh15</html>",
                                                                        "E":"<html><u>subindex E</u>:ADCCh16</html>",
                                                                        "F":"<html><u>subindex F</u>:ADCCh17</html>",
                                                                        "10":"<html><u>subindex 10</u>:ADCCh18</html>",
                                                                        "11":"<html><u>subindex 11</u>:ADCCh19</html>",
                                                                        "12":"<html><u>subindex 12</u>:ADCCh20</html>",
                                                                        "13":"<html><u>subindex 13</u>:ADCCh21</html>",
                                                                        "14":"<html><u>subindex 14</u>:ADCCh22</html>",
                                                                        "15":"<html><u>subindex 15</u>:ADCCh23</html>",
                                                                        "16":"<html><u>subindex 16</u>:ADCCh24</html>",
                                                                        "17":"<html><u>subindex 17</u>:ADCCh25</html>",                                                    
                                                                        "18":"<html><u>subindex 18</u>:ADCCh26</html>",
                                                                        "19":"<html><u>subindex 19</u>:ADCCh27</html>",
                                                                        "1A":"<html><u>subindex 1A</u>:ADCCh28</html>",
                                                                        "1B":"<html><u>subindex 1B</u>:ADCCh29</html>",
                                                                        "1C":"<html><u>subindex 1C</u>:ADCCh30</html>",
                                                                        "1D":"<html><u>subindex 1D</u>:ADCCh31</html>",                                                     
                                                                        "1E":"<html><u>subindex 1E</u>:ADCCh32</html>",
                                                                        "1F":"<html><u>subindex 20</u>:ADCCh33</html>",
                                                                        "20":"<html><u>subindex 21</u>:ADCCh34</html>"}}}
